vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        profil:
            uri_prefix: /images/profils
            upload_destination: '%kernel.project_dir%/public/images/profils'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
